/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_et_util_glesdriver_NativeGLESTools */

#ifndef _Included_com_et_util_glesdriver_NativeGLESTools
#define _Included_com_et_util_glesdriver_NativeGLESTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_et_util_glesdriver_NativeGLESTools
 * Method:    getShaderInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_et_util_glesdriver_NativeGLESTools_getShaderInfoLog
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
